name: Create Release

on:
  workflow_dispatch:
    inputs:
      FILE_URL:
        description: 'URL of the file to download'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize repo
        run: |
          mkdir -p workspace
          cd workspace

      - name: Download Files
        run: |
          cd workspace
          wget ${{ inputs.FILE_URL }}

      - name: Upload to Release
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        with:
          files: |
            workspace/*.zip
          name: Release (PBRP)
          tag_name: 'latest'
          body: |
            File uploaded from URL: ${{ inputs.FILE_URL }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
